version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: aitemplate-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: aitemplate_db
    ports:
      - "3306:3306"
    networks:
      - ait-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: aitemplate-redis
    ports:
      - "6379:6379"
    networks:
      - ait-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    container_name: aitemplate-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - ait-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
    container_name: aitemplate-app
    ports:
      - "8080:8080"
    networks:
      - ait-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    restart: always

networks:
  ait-network:
    driver: bridge
